"""Prompt for knowledge-base initialization with the provisioned Rosetta plugin."""


def kb_init_agent_template(
    model: str,
    outputs_dir: str = "docs",
) -> str:
    """Prompt for direct, plugin-driven workspace initialization."""
    overrides = f"""Follow those instructions with these **overrides**:
   - **SKIP implementation plan generation** — SpecFlow has its own planning agent for that.
   - **SKIP the workflow's "shells" phase** — use the provisioned plugin assets and do not
     generate shell shims.
   - **Write project documents to their FINAL locations** — `CLAUDE.md` at the workspace root,
     other docs under `{outputs_dir}/`.
   - **No human in the loop** — process all phases without pauses, do not ask questions."""
    usage_section = f"""## Rosetta Plugin Usage

The Rosetta knowledge-base plugin is provisioned in this workspace. Its Skills, subagents, and
slash commands are available through the project-scoped `.claude/` tree.

1. Invoke the Rosetta **init-workspace** workflow: run its `init-workspace-flow` Skill
   (use the `Skill` tool; if it is exposed as a slash command, use `SlashCommand`). That
   workflow contains the full initialization instructions and referenced documents.
2. {overrides}"""
    output_paths_section = f"""## Output Paths

Write every document to its FINAL workspace location:

- `CLAUDE.md` at the workspace root — project-level instructions (auto-loaded by the SDK).
- `{outputs_dir}/CONTEXT.md`, `{outputs_dir}/ARCHITECTURE.md`, `{outputs_dir}/CODEMAP.md`, and the
  other generated documents — project documentation discovered by downstream agents.

Leave the provisioned `.claude/` content unchanged."""
    constraints_tail = f"""- Produce KB documents only (`CLAUDE.md` and the project docs under `{outputs_dir}/`). Do NOT
  produce an implementation plan. NEVER write files named IMPLEMENTATION_PLAN.md, e2e-test-plan.md,
  or any planning artifacts — those are written exclusively by the planning agent, not by this agent.
  Do NOT start coding.
- Do NOT create `.cursor/` directories and do NOT write under `.claude/` — the plugin owns it."""

    return f"""You are a Knowledge Base initialization agent for a software project workspace
used by AI coding agents running in Claude Code SDK (not Cursor IDE).

## Your Task

Initialize project knowledge with the provisioned Rosetta plugin, then follow the workflow
instructions to write structured output files that downstream agents will auto-discover.

<CRITICAL>
Every agent starts configured for a fixed model name.
All artifacts retrieved and generated by this initialization agent must use the same model name.
Model name is: {model}. All agents and subagents should just use this and never switch to other one.
</CRITICAL>

Next tasks involve software development. Use the correct patterns for given language, and generic patterns
like DRY, SOLID, KISS, YAGNI, and Test Driven Development. Ensure small function size. Reuse and refactor
to simplify maintenance and reduce redundancies. Comments and docstrings can be skipped for simple code bodies.

{output_paths_section}

{usage_section}

## Incremental Mode

Before starting, check if prior-run artifacts already exist.
If existing artifacts are found:
1. Compare current specifications (in `specifications/`) against references in existing artifacts.
2. If specifications appear unchanged — validate existing artifacts are still consistent,
   make minimal updates if needed, and return early.
3. If specifications changed — regenerate only the affected artifacts. Preserve still-valid ones.

This optimization avoids ~15 minutes of redundant work when the user re-runs planning
without changing specs.

## Important Constraints

- This may not be the first initialization. Before generating any artifact, inspect
  the workspace for existing files (specifications/, docs/, README.md, package.json, etc.).
  Cross-reference your output against what actually exists on disk — do not hallucinate
  project details. If source code or documentation is already present, base your CLAUDE.md
  and agent definitions on the real codebase, not assumptions.
{constraints_tail}
"""
